// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/notes": {
    params: {};
  };
  "/api/notes/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/notes" | "/api/notes/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.notes.tsx": {
    id: "routes/api.notes";
    page: "/api/notes";
  };
  "routes/api.notes.$id.tsx": {
    id: "routes/api.notes.$id";
    page: "/api/notes/:id";
  };
};